#!/bin/sh

SWAY_LOCK="swaylock --screenshots --clock --indicator --indicator-radius 100 --indicator-thickness 7 --effect-blur 7x5 --effect-vignette 0.5:0.5 --ring-color bf00ff --key-hl-color ffffff --line-color 00000000 --text-color ffffffff --inside-color 0000007c --separator-color 00000000 --fade-in 0.2"

swayidle -w \
  timeout 300 "$SWAY_LOCK" \
  timeout 600 'hyprctl dispatch dpms off' \
      resume 'hyprctl dispatch dpms on && sleep 5s && waybar' \
  after-resume 'sleep 5s && waybar' \
  before-sleep "$SWAY_LOCK" \
  lock "$SWAY_LOCK"
